domain_path: C:\FPGA_ws\vitis_ws\AdcTest_PS\platform\export\platform\sw\freertos_psu_cortexr5_1
app_src_dir: C:\Xilinx\Vitis\2024.2\data\embeddedsw\lib\sw_apps\empty_application
template: empty_application
lang: c
